configfile: 'config/config_download.yml'

#rule all_bids_mri:
#    input:
#        expand('bids/site-{site}/dataset_description.json',site=config['sites'])






wildcard_constraints:
    subject='[a-zA-Z0-9]+',
    site='LHS|TWH|HSC'

if config['update_lists']:
       
    include: 'rules/update_lists.smk'
else:
    include: 'rules/download.smk'
    include: 'rules/bids_eeg.smk'

#include: 'rules/bids_mri.smk'
include: 'rules/singularity.smk'
