update_lists: False


spred_url: 'https://spred.braincode.ca/spred/'
sites:
  - LHS
  - TWH
  - HSC

ignore_experiments:
  - 'EPL31_LHS_0011_02_SE04_EEG'
  - 'EPL31_LHS_0016_02_SE04_EEG'
  - 'EPL31_LHS_0005_01_SE07_EEG'
  - 'EPL31_HSC_0001_01_SE01_EEG'
  - 'EPL31_LHS_0025_01_SE04_EEG'
  - 'EPL31_LHS_0004_02_SE01_EEG'
  - 'EPL31_LHS_0028_01_SE08_EEG'
  - 'EPL31_TWH_0023_01_SE03_EEG'
  - 'EPL31_LHS_0007_01_SE11_EEG'
  - 'EPL31_LHS_0029_01_SE02_EEG'
  - 'EPL31_LHS_0012_02_SE06_EEG'
  - 'EPL31_LHS_0012_02_SE05_EEG'
  - 'EPL31_LHS_0025_02_SE03_EEG'
  - 'EPL31_LHS_0030_01_SE17_EEG'
  - 'EPL31_LHS_0004_01_SE01_EEG'
  - 'EPL31_LHS_0007_01_SE13_EEG'
  - 'EPL31_LHS_0025_01_SE05_EEG'
  - 'EPL31_LHS_0012_02_SE12_EEG'
  - 'EPL31_LHS_0011_02_SE11_EEG'
  - 'EPL31_LHS_0031_03_SE05_EEG'
  - 'EPL31_LHS_0012_02_SE11_EEG'
  - 'EPL31_LHS_0026_01_SE03_EEG'
  - 'EPL31_LHS_0012_02_SE09_EEG'


tmp_download: '/localscratch'


tar2bids:
  HSC: 'resources/heuristics/hsc_eplink.py'
  LHS: 'resources/heuristics/cfmm_lhs_eplink.py'
  TWH: 'resources/heuristics/twh_eplink.py'

containers:
  tar2bids: 'docker://khanlab/tar2bids:v0.0.6b'
